vtex/shoreline

packages/admin-ui-docs/docusaurus.config.js

Update GitHub repository URL in documentation config (change **onda** repository to **admin-ui**)

docs: update github repository url

---

packages/admin-ui-react/src/__tests__/createSystem.test.tsx
packages/admin-ui-react/src/createSystem.tsx
packages/gatsby-plugin-admin-ui/src/provider.js

In the `createSystem` function, I've:
- Added the `experimentalDisabledGlobalStyles`
- Replaced the `__theme` property for `experimentalTheme`
- Replaced the `emotionInstance` property for `experimentalEmotionOptions`
`admin-ui` users must be able to quickly identify experimental/unstable parts of the code. The `experimental` flag must be added as a prefix on these parts.
```jsx
import { createSystem } from '@vtex/admin-ui'
const [ThemeProvider] = createSystem({
key: 'example',
experimentalDisabledGlobalStyles: true,
})
```
User will have breaking changes with:
**Before:**
```jsx
import { createSystem } from '@vtex/admin-ui'
const customTheme = {}
const [ThemeProvider] = createSystem({
key: 'example',
__theme: customTheme,
})
```
**After:**
```jsx
import { createSystem } from …
```

feat(react): add experimentalDisabledGlobalStyles prop to createSystem

---

.circleci/config.yml
package.json
packages/admin-ui/package.json

Adds the Circle CI configuration so we can run the build and the test for the following packages in every commit:
- `@vtex/admin-ui`
- `@vtex/admin-ui-react`
- `@vtex/admin-ui-core`
For now, I would go with only these 3 packages, so we can test the Circle CI limits and check if it fits well in our project

ci(circle): add circle ci workflow

---

packages/admin-ui-docs/docs/components/collapsible.md
packages/admin-ui/package.json
packages/admin-ui/src/components/Collapsible/__stories__/Collapsible.stories.tsx
packages/admin-ui/src/components/Collapsible/__tests__/Collapsible.test.tsx
packages/admin-ui/src/components/Collapsible/__tests__/__snapshots__/Collapsible.test.tsx.snap
packages/admin-ui/src/components/Collapsible/components/Collapsible.tsx
packages/admin-ui/src/components/Collapsible/components/CollapsibleContent.tsx
packages/admin-ui/src/components/Collapsible/components/CollapsibleHeader.tsx
packages/admin-ui/src/components/Collapsible/context.tsx
packages/admin-ui/src/components/Collapsible/hooks/useCollapsibleState.ts
packages/admin-ui/src/components/Collapsible/index.tsx
packages/admin-ui/src/components/CollapsibleGroup/CollapsibleGroup.test.tsx
packages/admin-ui/src/components/CollapsibleGroup/__snapshots__/CollapsibleGroup.test.tsx.snap
yarn.lock

fix #32 
Add animation to collapsible
yarn and yarn test
https://admin-ui-docs-git-feature-collapse-animation-styleguide-core.vercel.app/components/collapsible
run storybook

Feature collapsible animation

---

packages/admin-ui-docs/docs/components/menu.md

fix #38 
Improve docs
Fix issue #38 
check built docs

docs(menuitem): improve props documentation

---

packages/admin-ui-core/src/aliases.ts
packages/admin-ui/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap

Responsive aliases where causing strange behaviors

fix(core): responsive aliases values

---

packages/admin-ui-docs/docusaurus.config.js
packages/admin-ui-docs/src/components/FilterDataGrid/styles.ts

Fix z-index of algolia modal search

fix: set z-index for algolia modal search

---

packages/admin-ui-docs/docs/experimental/combobox.mdx
packages/admin-ui/package.json
packages/admin-ui/src/combobox/combobox-field.tsx
packages/admin-ui/src/combobox/combobox-item.ts
packages/admin-ui/src/combobox/combobox-popover.tsx
packages/admin-ui/src/combobox/combobox.i18n.ts
packages/admin-ui/src/combobox/combobox.state.ts
packages/admin-ui/src/combobox/combobox.stories.tsx
packages/admin-ui/src/combobox/combobox.style.ts
packages/admin-ui/src/combobox/index.ts
packages/admin-ui/src/experimental.ts
packages/admin-ui/src/i18n/index.ts
packages/admin-ui/src/i18n/locales.ts
packages/admin-ui/src/i18n/react-aria-i18n.ts
yarn.lock

Add experimental combobox

---

.storybook/preview.js
packages/admin-ui-core/src/tokens/text.ts
packages/admin-ui-core/src/values/typography.ts
packages/admin-ui-react/src/createIcons.tsx
packages/admin-ui/src/components/AbstractInput/__snapshots__/AbstractInput.test.tsx.snap
packages/admin-ui/src/components/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
packages/admin-ui/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
packages/admin-ui/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/admin-ui/src/components/Collapsible/__tests__/__snapshots__/Collapsible.test.tsx.snap
packages/admin-ui/src/components/CollapsibleGroup/__snapshots__/CollapsibleGroup.test.tsx.snap
packages/admin-ui/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/admin-ui/src/components/FilterBar/__tests__/__snapshots__/FilterBar.test.tsx.snap
packages/admin-ui/src/components/Input/__snapshots__/Input.test.tsx.snap
packages/admin-ui/src/components/InputPassword/__snapshots__/InputPassword.test.tsx.snap
packages/admin-ui/src/components/Menu/__snapshots__/Menu.test.tsx.snap
packages/admin-ui/src/components/NumericStepper/__snapshots__/NumericStepper.test.tsx.snap
packages/admin-ui/src/components/Page/__tests__/__snapshots__/PageHeader.test.tsx.snap
packages/admin-ui/src/components/Search/__tests__/__snapshots__/Search.test.tsx.snap
packages/admin-ui/src/components/Select/__snapshots__/Select.test.tsx.snap
packages/admin-ui/src/components/Sidebar/__stories__/Sidebar.stories.tsx
packages/admin-ui/src/components/Sidebar/components/Sidebar.tsx
packages/admin-ui/src/components/Sidebar/components/SidebarBackdrop.tsx
packages/admin-ui/src/components/Sidebar/components/SidebarDisclosure.tsx
packages/admin-ui/src/components/Sidebar/components/SidebarItem.tsx
packages/admin-ui/src/components/Sidebar/components/SidebarSection.tsx
packages/admin-ui/src/components/Sidebar/components/SidebarSectionItem.tsx
packages/admin-ui/src/components/Sidebar/hooks/useSidebarState.ts
packages/admin-ui/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
packages/admin-ui/src/components/Tag/__snapshots__/Tag.test.tsx.snap
packages/admin-ui/src/components/Toast/__tests__/__snapshots__/Toast.test.tsx.snap

Apply design improvements on the Sidebar component based on VTEX client's feedback
List of improvements:
* Apply spacing changes over the section and section items
* Change the sidebar behavior to show a preview of each section items when hovering over the section's icon
1. Check that the spacing of the section items changes between the old version and the new one
2. Hover the icons using your mouse to check the section preview
3. Hover with your mouse on the last section and see that the URL preview doesn't override the icon
> 💡 You can type "a", "s", and "t" to hide storybook gadgets.
**Before**
You can check this [storybook workspace](https://leftnav-before.surge.sh/?path=/story/admin-ui-sidebar--playground) for a preview without the changes applied.
**After**
You can check the …

Sidebar design & behavior improvements

---

packages/admin-ui-react/package.json
packages/admin-ui/package.json
yarn.lock

Update @vtex/phosphor-icons version to improve bundle size of admin-ui

build: bump phosphor icons version

---

packages/admin-ui-docs/docusaurus.config.js

Add google analytics to our documentation
We are not tracking access to our documentation

feat: add google analytics to our documentation

---

packages/admin-ui-docs/docs/help/release-notes.md
packages/admin-ui-docs/src/components/StatusTable/components.tsx

docs: update release notes table

---

packages/admin-ui-core/src/types.ts
packages/admin-ui-core/src/values/styleKit.ts
packages/admin-ui-docs/docs/experimental/inline.mdx
packages/admin-ui-util/src/types.ts
packages/admin-ui/src/experimental.ts
packages/admin-ui/src/inline/__snapshots__/inline.test.tsx.snap
packages/admin-ui/src/inline/index.ts
packages/admin-ui/src/inline/inline.stories.tsx
packages/admin-ui/src/inline/inline.test.tsx
packages/admin-ui/src/inline/inline.tsx

Inline experimental component

---

packages/admin-ui-docs/docs/experimental/bleed.mdx
packages/admin-ui/src/bleed/__snapshots__/bleed.test.tsx.snap
packages/admin-ui/src/bleed/bleed.stories.tsx
packages/admin-ui/src/bleed/bleed.test.tsx
packages/admin-ui/src/bleed/bleed.tsx
packages/admin-ui/src/bleed/index.ts
packages/admin-ui/src/experimental.ts

Add the bleed component as experimental

Bleed experimental component

---

packages/admin-ui-docs/docs/guidelines/responsive-design.md

Improve the content of the responsive-design page.

docs(responsive): improve content

---

packages/admin-ui-docs/docusaurus.config.js
packages/admin-ui-docs/src/css/custom.scss
packages/admin-ui-docs/src/css/sidebar.scss
packages/admin-ui-docs/src/theme/Footer/index.js
packages/admin-ui-docs/src/theme/Footer/styles.module.scss

Create documentation [footer](https://www.figma.com/file/hcO2T1NcrgGZelG6TvAtKn/Documentation?node-id=831%3A264431)
Check in the preview link. At the current moment, we are not showing the links footer as **Privacy**, **Terms of use** and others because we do not have all the internal links, so @davicostalf asked to not show them now, **but the footer is already prepared for showing those links in the future.**

feat: create documentation footer

---

packages/admin-ui/src/components/Sidebar/__stories__/Sidebar.stories.tsx
packages/admin-ui/src/components/Sidebar/components/Sidebar.tsx
packages/admin-ui/src/components/Sidebar/components/SidebarDisclosure.tsx
packages/admin-ui/src/components/Sidebar/components/SidebarSection.tsx

Add spacing adjustments to the Sidebar component

fix(sidebar): adjust spacing according to design specs

---

packages/admin-ui-core/src/types.ts
packages/admin-ui-docs/docs/guidelines/components/inline.mdx
packages/admin-ui-docs/docs/guidelines/experimental/bleed.mdx
packages/admin-ui/src/experimental.ts
packages/admin-ui/src/index.ts
packages/admin-ui/src/inline/inline.stories.tsx
packages/admin-ui/src/inline/inline.tsx

Promote `Inline` from experimental:
- The `unit` prop is removed
- The token autocompletion is improved

feat(inline): promote component

---

packages/admin-ui/src/filters/__tests__/__snapshots__/filter-multiple.test.tsx.snap
packages/admin-ui/src/filters/__tests__/__snapshots__/filter.test.tsx.snap
packages/admin-ui/src/filters/filter-disclosure.style.tsx

Fix filter disclosure style bug.
Bug
Check storybook + yarn test

fix(filter disclosure): fix filter diclosure children order

---

packages/admin-ui-docs/src/components/PageSection/index.tsx
packages/admin-ui-docs/src/components/PageSection/styles.scss

Create the base section to compose more complex sections of components page

feat(page section): create base section for the docs page

---

packages/admin-ui-codemod/bin/admin-ui-codemod.js
packages/admin-ui-codemod/package.json

- Users were experiencing errors while running codemods with npx. This Pr fixes this

fix(codemod): fix imports and engines

---

packages/admin-ui-docs/docs/guidelines/components/tabs.mdx

NAD-1091 docs(tabs): add design ref tab

---

packages/admin-ui-docs/docs/guidelines/components/modal.mdx

NAD-1087 docs(modal): add design reference tab

---

packages/admin-ui-docs/docs/guidelines/components/toggle.mdx

NAD-1095 docs(toggle): add design ref tab

---

packages/admin-ui-docs/docs/guidelines/components/checkbox.mdx

docs(checkbox): add design reference tab

---

packages/admin-ui-docs/docs/guidelines/components/alert.mdx
packages/admin-ui-docs/docs/guidelines/components/card.mdx
packages/admin-ui-docs/docs/guidelines/components/select.mdx

Update Card docs
Lack of design content tab.
See link below.
n/a

NAD-1081 docs(card): add design reference tab

---

packages/admin-ui-docs/docs/guidelines/experimental/date-picker.mdx

NAD-1084 docs(datepicker): add design reference tab

---

packages/admin-ui-docs/docs/guidelines/components/anchor.mdx

Add design reference for Anchor.

NAD-1086 docs(anchor): add design ref tab

---

packages/admin-ui-docs/docs/guidelines/components/numeric-stepper.mdx

NAD-1090 docs(numeric stepper): add design ref tab

---

packages/admin-ui-docs/docs/guidelines/components/tag.mdx

NAD-1092 docs(tag): add design ref tab

---

packages/admin-ui-docs/docs/guidelines/components/text-area.mdx

NAD-1093 docs(textarea): add design ref tab

---

packages/admin-ui-docs/docs/guidelines/components/toast.mdx

NAD-1094 docs(toast): add design ref tab

---

packages/admin-ui-docs/docs/guidelines/components/tooltip.mdx

NAD-1096 docs(tooltip): add design ref tab

---

packages/admin-ui-docs/docs/guidelines/components/select.mdx

NAD-1089 docs(select): add design ref tab

---

packages/admin-ui-docs/docs/guidelines/components/button.mdx

NAD-1082 Feature/button design ref

---

packages/admin-ui-docs/docs/guidelines/foundations/colors.mdx

fix(docs): improve color semantics

---

packages/formik/src/components/FormikCheckbox/FormikCheckbox.test.tsx
packages/formik/src/components/FormikCheckboxGroup/FormikCheckboxGroup.test.tsx
packages/formik/src/components/FormikInput/FormikInput.test.tsx
packages/formik/src/components/FormikInputPassword/FormikInputPassword.test.tsx
packages/formik/src/components/FormikNumericStepper/FormikNumericStepper.test.tsx
packages/formik/src/components/FormikRadio/FormikRadioGroup.test.tsx
packages/formik/src/components/FormikSelect/FormikSelect.test.tsx
packages/formik/src/components/FormikTextArea/FormikTextArea.test.tsx
packages/formik/src/components/FormikToggle/FormikToggle.test.tsx

As the title says
Because of this error, the tests were running forever when running `git push`.

test(formik): fix eslint error on admin-formik tests

---

packages/admin-ui-docs/docs/teams/developing/comparison.mdx

Out of date concept and broken links

Fix old references to themeKeys on docs

---

packages/admin-ui-docs/docs/guidelines/components/button.mdx
packages/admin-ui-docs/src/components/BestPractices.tsx
packages/admin-ui-docs/src/components/Page/index.tsx
packages/admin-ui-docs/src/theme/CodeBlock/index.js
packages/admin-ui-docs/src/theme/Playground/index.js
packages/admin-ui-docs/src/theme/Playground/styles.module.scss

Add BestPractices component that represents the Do's and Don'ts of a component
[Figma Link](https://www.figma.com/file/hcO2T1NcrgGZelG6TvAtKn/Documentation?node-id=794%3A262617)
[Check the implementation preview in the Design tab of the Button documentation](https://admin-ui-docs-9nimn3dzj-styleguide-core.vercel.app/guidelines/components/button)

docs(best-practices): add BestPractices component

---

packages/admin-ui/src/components/Sidebar/components/SidebarBackdrop.tsx

fix(sidebar): change sidebar backdrop button icon color

---

packages/admin-ui/src/button/button.style.ts
packages/admin-ui/src/button/button.tsx
packages/admin-ui/src/components/AbstractInput/__snapshots__/AbstractInput.test.tsx.snap
packages/admin-ui/src/components/InputPassword/__snapshots__/InputPassword.test.tsx.snap
packages/admin-ui/src/components/NumericStepper/__snapshots__/NumericStepper.test.tsx.snap
packages/admin-ui/src/components/Page/__tests__/__snapshots__/PageHeader.test.tsx.snap
packages/admin-ui/src/components/Tag/__snapshots__/Tag.test.tsx.snap
packages/admin-ui/src/components/Toast/__tests__/__snapshots__/Toast.test.tsx.snap

[It solves this issue reported in the admin-ui channel.](https://vtex-dev.atlassian.net/jira/software/c/projects/AU/boards/660?modal=detail&selectedIssue=AU-136)
Check that the button with an icon only is centered in the Button documentation

fix(button): adjust spacing when it has only an icon as children

---

packages/admin-ui-core/src/values/styleKit.ts
packages/admin-ui/src/button/__snapshots__/button.test.tsx.snap
packages/admin-ui/src/components/AbstractInput/__snapshots__/AbstractInput.test.tsx.snap
packages/admin-ui/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
packages/admin-ui/src/components/Collapsible/__tests__/__snapshots__/Collapsible.test.tsx.snap
packages/admin-ui/src/components/CollapsibleGroup/__snapshots__/CollapsibleGroup.test.tsx.snap
packages/admin-ui/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
packages/admin-ui/src/components/FilterBar/__tests__/__snapshots__/FilterBar.test.tsx.snap
packages/admin-ui/src/components/Input/__snapshots__/Input.test.tsx.snap
packages/admin-ui/src/components/InputPassword/__snapshots__/InputPassword.test.tsx.snap
packages/admin-ui/src/components/Menu/__snapshots__/Menu.test.tsx.snap
packages/admin-ui/src/components/NumericStepper/__snapshots__/NumericStepper.test.tsx.snap
packages/admin-ui/src/components/Page/__tests__/__snapshots__/PageHeader.test.tsx.snap
packages/admin-ui/src/components/Search/__tests__/__snapshots__/Search.test.tsx.snap
packages/admin-ui/src/components/Select/__snapshots__/Select.test.tsx.snap
packages/admin-ui/src/components/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
packages/admin-ui/src/components/Tag/__snapshots__/Tag.test.tsx.snap
packages/admin-ui/src/components/TextArea/__snapshots__/TextArea.test.tsx.snap
packages/admin-ui/src/components/Toast/__tests__/__snapshots__/Toast.test.tsx.snap
packages/admin-ui/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
packages/admin-ui/src/filters/__tests__/__snapshots__/filter-multiple.test.tsx.snap
packages/admin-ui/src/filters/__tests__/__snapshots__/filter.test.tsx.snap
packages/admin-ui/src/radio/__snapshots__/radio.test.tsx.snap

fix(admin-ui): update focus-ring to the latest specs

---

packages/admin-ui-docs/docs/guidelines/components/button.mdx
packages/admin-ui-docs/src/components/BestPractices.tsx
packages/admin-ui-docs/src/components/List.tsx
packages/admin-ui-docs/src/components/OrderedList.tsx
packages/admin-ui-docs/src/components/Page/styles.scss
packages/admin-ui-docs/src/components/PageSection/styles.scss

Add List component to be used within the PageSection with a list only
[Figma Link](https://www.figma.com/file/hcO2T1NcrgGZelG6TvAtKn/Documentation?node-id=794%3A262617)
Check the design tab on the Button documentation

docs(list-section): add list component

---

.circleci/config.yml

I had to remove the cache steps when doing the change of the build system. Now is all good to have this step back

ci(circle): add cache steps to the jobs

---

packages/admin-ui-form/package.json
packages/admin-ui-form/src/form/form.state.ts
packages/admin-ui-form/src/form/stories/form.stories.tsx
packages/admin-ui-form/src/index.ts
packages/admin-ui-form/src/resolvers/index.ts
packages/admin-ui-form/src/resolvers/stories/yup.stories.tsx
packages/admin-ui-form/src/resolvers/yup.ts
packages/admin-ui-form/src/text-input/index.ts
packages/admin-ui-form/src/text-input/stories/text-input.stories.tsx
packages/admin-ui-form/src/text-input/text-input.tsx
packages/admin-ui-form/src/util/dx.ts
packages/admin-ui-form/src/util/error.ts
packages/admin-ui-form/src/util/index.ts
packages/admin-ui-form/src/watch/use-watch.ts
yarn.lock

- Added text-input to admin-ui-forms
- Added dx utils
- Added validation rules
- Added yup resolvers

Admin UI Form: Integrate text-input & improve validation rules

---

packages/admin-ui/src/next.ts
packages/admin-ui/src/text-area/index.ts
packages/admin-ui/src/text-area/stories/text-area.stories.tsx
packages/admin-ui/src/text-area/text-area-constants.ts
packages/admin-ui/src/text-area/text-area-container.ts
packages/admin-ui/src/text-area/text-area-element.ts
packages/admin-ui/src/text-area/text-area.style.ts
packages/admin-ui/src/text-area/text-area.tsx
packages/admin-ui/src/text-area/use-text-area.ts
packages/admin-ui/src/text-area/useTextArea.ts

Add a reviewed version of the TextArea component
Check storybook

feat(textarea): add reviewed text area component

---

packages/admin-ui-form/src/form/stories/form.stories.tsx
packages/admin-ui-form/src/resolvers/stories/yup.stories.tsx
packages/admin-ui-form/src/text-area/index.ts
packages/admin-ui-form/src/text-area/stories/text-area.stories.tsx
packages/admin-ui-form/src/text-area/text-area.tsx
packages/admin-ui-form/src/util/dx.ts
packages/admin-ui/src/text-area/text-area.style.ts

Integrate text area to admin ui form
Check stories yup, text-area and form under `admin-ui-form`

Feat integrate text area

---

packages/admin-ui-docs/docs/introduction/release-notes.mdx
packages/admin-ui-docs/src/components/ReleaseNotes.tsx

As the title says
Updates the release notes doc page automatically whenever a release is created
Just check for the release notes page

docs(release-notes): integrate release notes page with github api

---

packages/admin-ui-docs/docs/teams/developing/code-styleguide.mdx

docs(code-styleguide): update to new specs

---

packages/admin-ui-form/package.json
yarn.lock

- Fix typescript declarations
- Improve compatibility w/ VTEX IO

fix(admin-ui-form): improve compatibility w/ VTEX IO and fix typescript

---

README.md

docs(readme): update packages

---

packages/admin-ui-docs/docs/guidelines/components/number-input.mdx

Add `NumberInput` documentation
The `NumberInput` documentation was removed for some possible rebase.
Check the preview

docs: add number-input documentation

---

packages/admin-ui-docs/docs/guidelines/components/page.mdx
packages/admin-ui-docs/docs/guidelines/components/table.mdx
packages/admin-ui-docs/src/components/FilterTable/index.tsx
packages/admin-ui-docs/src/components/FilterTable/styles.ts
packages/admin-ui-docs/src/components/PageHeader/links.ts
packages/admin-ui-docs/src/components/ReleaseNotes.tsx
packages/admin-ui-docs/src/components/SemanticTable.tsx
packages/admin-ui-docs/src/components/StatusTable/components.tsx
packages/admin-ui-docs/src/components/StatusTable/index.tsx
packages/admin-ui-docs/src/components/TokensTable/index.tsx
packages/admin-ui-docs/src/components/Typeface.tsx
packages/admin-ui/src/components/Page/__stories__/Page.stories.tsx
packages/admin-ui/src/index.ts
packages/admin-ui/src/table/components/table-body.tsx
packages/admin-ui/src/table/components/table-cell.tsx
packages/admin-ui/src/table/components/table-head.tsx
packages/admin-ui/src/table/components/table.tsx
packages/admin-ui/src/table/context.tsx
packages/admin-ui/src/table/create-columns.ts
packages/admin-ui/src/table/hooks/use-table-sort.ts
packages/admin-ui/src/table/hooks/use-table-state.tsx
packages/admin-ui/src/table/resolvers/base.tsx
packages/admin-ui/src/table/resolvers/image.tsx
packages/admin-ui/src/table/resolvers/resolver-core.tsx
packages/admin-ui/src/table/stories/complexity.stories.tsx
packages/admin-ui/src/table/stories/dataview.stories.tsx
packages/admin-ui/src/table/stories/dnd.stories.tsx
packages/admin-ui/src/table/stories/selectable.stories.tsx
packages/admin-ui/src/table/stories/sortable.stories.tsx
packages/admin-ui/src/table/types.tsx

Check the `admin-ui-review/table` stories.

feat(table): rename DataGrid to Table

---

packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/input-password.mdx
packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/input.mdx
packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/numeric-stepper.mdx
packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/select.mdx
packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/text-area.mdx

docs(admin-ui): disable live view for deprecated/removed components

---

packages/admin-ui/src/filters/filter-applied-items-label.tsx
packages/admin-ui/src/filters/filter-applied-list-label.tsx
packages/admin-ui/src/filters/filter-base.tsx
packages/admin-ui/src/filters/filter-disclosure.tsx
packages/admin-ui/src/filters/filter-multiple/filter-multiple-search.tsx
packages/admin-ui/src/filters/filter-multiple/filter-multiple.tsx
packages/admin-ui/src/filters/filter-searchbox.tsx
packages/admin-ui/src/filters/filter.style.tsx
packages/admin-ui/src/filters/filter/filter-radio.tsx
packages/admin-ui/src/filters/filter/filter-search.tsx
packages/admin-ui/src/filters/filter/filter.tsx

Reduce some code repetition + separate disclosure from base filter structure, that will be helpful when implementing different states.
Check filters on built storybook

Reorg filter label

---

packages/admin-ui-docs/docs/introduction/developing/contributing.mdx

docs(contributing): add ways of contributing to admin ui

---

packages/admin-ui/src/menu/menu.test.tsx

test: create menu tests

---

packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/menu.mdx

Replace live editor with static code block in the previous menu docs version
Check the documentation preview

docs: replace live editor with static code block in menu docs

---

packages/admin-ui-docs/content/text-input/code.mdx
packages/admin-ui-docs/content/text-input/design.mdx
packages/admin-ui-docs/content/text-input/overview.mdx
packages/admin-ui-docs/content/text-input/toc.js
packages/admin-ui-docs/docs/guidelines/components/text-input.mdx

docs(text-input): add docs page

---

packages/admin-ui-docs/content/text-area/code.mdx
packages/admin-ui-docs/content/text-area/design.mdx
packages/admin-ui-docs/content/text-area/overview.mdx
packages/admin-ui-docs/content/text-area/toc.js
packages/admin-ui-docs/docs/guidelines/components/text-area.mdx

docs(text-area): add docs page

---

packages/admin-ui-docs/src/components/CodePreviewContainer/styles.scss

Fix the table inside the code preview

fix: reset table style inside the code preview

---

packages/admin-ui/src/select/select.i18n.tsx

Add placeholder label of the Select component from admin-ui design system . Requested in[ LOC-8488](https://vtex-dev.atlassian.net/browse/LOC-8488)

Add Select translations

---

packages/admin-ui/src/menu/menu.state.ts

Improve menu state wrapper and its typing

refactor: improve menu state wrapper and its typing

---

packages/admin-ui-docs/versioned_docs/version-0.131.0/guidelines/components/data-grid.mdx

Remove preview code live mode
Check the Data Grid docs

docs(data-grid): remove preview code live mode

---

packages/admin-ui-docs/content/form/code.mdx
packages/admin-ui-docs/content/form/overview.mdx
packages/admin-ui-docs/content/form/toc.js
packages/admin-ui-docs/docs/guidelines/components/form.mdx
packages/admin-ui-docs/src/components/Section/index.tsx
packages/admin-ui-docs/src/components/Section/styles.scss
packages/admin-ui-docs/src/theme/ReactLiveScope/index.js

Add admin-ui-form documentation

---

packages/admin-ui/src/menu/menu-button.tsx
packages/admin-ui/src/menu/menu-item.tsx

refactor: update menu labels typing to ReactNode

---

packages/admin-ui-docs/content/table/code.mdx
packages/admin-ui-docs/content/table/overview.mdx

update overview and code tabs content
Check the docs preview

docs(table): update overview and code tabs content

---

packages/admin-ui-docs/docs/guidelines/components/formik.mdx
packages/deprecated-formik/src/components/FormikCheckbox/index.tsx
packages/deprecated-formik/src/components/FormikCheckboxGroup/FormikCheckbox.tsx
packages/deprecated-formik/src/components/FormikCheckboxGroup/index.tsx
packages/deprecated-formik/src/components/FormikInput/index.tsx
packages/deprecated-formik/src/components/FormikInputPassword/index.tsx
packages/deprecated-formik/src/components/FormikNumericStepper/index.tsx
packages/deprecated-formik/src/components/FormikRadio/FormikRadio.tsx
packages/deprecated-formik/src/components/FormikRadio/FormikRadioGroup.tsx
packages/deprecated-formik/src/components/FormikSelect/index.tsx
packages/deprecated-formik/src/components/FormikTextArea/index.tsx
packages/deprecated-formik/src/components/FormikToggle/index.tsx

The Formik library is no longer maintained by the admin-ui team and it's being replaced for a new solution based on the [React Hook Forms](https://react-hook-form.com/)

fix(formik): deprecate formik components

---

packages/admin-ui/package.json
yarn.lock

fix(icons): update phosphor-icons library

---

packages/admin-ui-docs/docs/guidelines/components/toast.mdx
packages/admin-ui-docs/docs/introduction/developing/migrating.mdx
packages/admin-ui-docs/docs/introduction/developing/quick-start.mdx

docs(emotion): remove emotion references from documentation

---

packages/admin-ui-docs/docs/guidelines/components/checkbox.mdx

docs(checkbox): fix code preview

---

packages/admin-ui/src/experimental.ts

Enable use of filterMultipleSearch
Missing filterMultipleSearch export 
Check docs and storybook

Fix filter export

---

packages/admin-ui-docs/src/components/Section/styles.scss

update section space between
The docs sections and their inner sections were widely spaced between them.

docs: update section space between

---

packages/admin-ui/src/alert/alert.tsx

Remove the left-margin of alert icon.
Check the doc preview of Alert.

fix(alert): update icon margin style

---

packages/admin-ui/src/filters/__stories__/filter.stories.tsx
packages/admin-ui/src/filters/__stories__/filters-searchable.stories.tsx
packages/admin-ui/src/filters/filter-footer.tsx
packages/admin-ui/src/filters/filter-listbox.tsx
packages/admin-ui/src/filters/filter-multiple/filter-option-checkbox.tsx
packages/admin-ui/src/filters/filter-popover-context.tsx
packages/admin-ui/src/filters/filter-searchbox.tsx
packages/admin-ui/src/filters/filter/filter-option-radio.tsx

Simplifly composable filters api by removing the need of state prop on all components inside popover.
Check storybook for filter and filtersearch stories

feat(filters): make state available through context on composite children

---

packages/admin-ui/src/page/page-header-menu-button.tsx
packages/admin-ui/src/page/page.style.ts

Fix page styling

---

packages/admin-ui/src/checkbox/checkbox.tsx
packages/admin-ui/src/filters/filter-footer.tsx
packages/admin-ui/src/filters/filter-listbox.tsx

Implement suggested improvements and fix filter checkbox spacing issue
Check for filter storybook

Chore filter code improvement

---

packages/admin-ui-docs/content/page/code.mdx
packages/admin-ui-docs/content/page/overview.mdx
packages/admin-ui-docs/docs/guidelines/components/page.mdx
packages/admin-ui-docs/versioned_docs/version-0.132.0/guidelines/components/page.mdx
packages/admin-ui/src/page/page.stories.tsx

Updates the page documentation for better 😉

docs(page): update overriden defaults data

---

packages/admin-ui/src/filters/filter-applied-items-label.tsx
packages/admin-ui/src/filters/filter-listbox.tsx
packages/admin-ui/src/filters/filter-searchbox.tsx

Prevent circular dependecies by fixing some imports
encouraged to add a more descriptive explanation. -->

fix(filters): fix imports to prevent circular dependencies

---

packages/admin-ui-core/src/aliases.ts
packages/admin-ui-core/src/stories/core.stories.tsx
packages/admin-ui-core/src/types.ts
packages/admin-ui-docs/docs/introduction/developing/styling.mdx

feat(fg-alias): add fg alias as a shorthand to the color css property

---

packages/admin-ui/src/filters/filter-disclosure.tsx

Improve some messy type differentiation code
Disclosures on storybook should work as before

refactor(filter disclosure): improve type differentiation

---

packages/admin-ui-core/src/helpers.ts
packages/admin-ui-core/src/stories/core.stories.tsx
packages/admin-ui-core/src/types.ts
packages/admin-ui-core/src/utils.ts
packages/admin-ui-docs/docs/introduction/developing/styling.mdx

Add `colorTheme` alias that will replace the external usage of the `palette` helper function

Add colorTheme csx alias

---

packages/admin-ui/src/components/Topbar/index.tsx

Fix an extra spacing in the Topbar skeleton which is causing a misalignment
**Before**
**After**
In the storybook preview
1. Go to the Sidebar story
2. Toggle the loading
3. Check that it's everything aligned

fix(topbar): adjust skeleton space to be according with the design specs

---

packages/admin-ui/src/button/button.style.ts
packages/admin-ui/src/button/button.tsx

- Update button to ariakit
- Fix button focus visible to match design.

fix(button): :focus-visible state must include :hover state

---

packages/admin-ui-docs/content/table/code.mdx
packages/admin-ui-docs/content/table/overview.mdx
packages/admin-ui/src/table/resolvers/base.tsx
packages/admin-ui/src/table/resolvers/menu.tsx
packages/admin-ui/src/table/resolvers/resolver-core.tsx
packages/admin-ui/src/table/stories/menu.stories.tsx

Add Table menu resolver to help in the addition of menus to the table row

feat(table): add menu resolver

---

packages/admin-ui/src/table/components/table-cell.tsx
packages/admin-ui/src/table/components/table-head.tsx
packages/admin-ui/src/table/components/table.tsx
packages/admin-ui/src/table/hooks/use-table-scroll.ts
packages/admin-ui/src/table/hooks/use-table-state.tsx
packages/admin-ui/src/table/stories/scroll.stories.tsx
packages/admin-ui/src/table/styles/table-cell.styles.ts
packages/admin-ui/src/table/styles/table-head.styles.ts
packages/admin-ui/src/table/styles/table-row.styles.ts

Add box-shadow on vertical and horizontal scroll inside the table
Check the horizontal and vertical scroll stories

feat(table): add box-shadow on vertical scroll

---

packages/admin-ui/src/table/components/table-body.tsx
packages/admin-ui/src/table/components/table-cell.tsx
packages/admin-ui/src/table/components/table-head.tsx
packages/admin-ui/src/table/components/table.tsx
packages/admin-ui/src/table/hooks/use-table-state.tsx
packages/admin-ui/src/table/styles/table-body.styles.ts
packages/admin-ui/src/table/styles/table-cell.styles.ts
packages/admin-ui/src/table/styles/table-head.styles.ts
packages/admin-ui/src/table/styles/table-row.styles.ts
packages/admin-ui/src/table/styles/table.styles.ts

update structure and scroll behavior to improve the "content fit" through `display: contents` 
Avoid fixing the column width to be able to show the column content

refactor(table): update structure and scroll behavior

---

packages/admin-ui-docs/content/table/overview.mdx
packages/admin-ui-docs/src/components/Page/styles.scss
packages/admin-ui-docs/src/css/markdown.scss

fix table in the code preview section
- [] Quality improvement (tests or refactors)

docs(table): fix table in the code preview section

---

packages/admin-ui-core/src/aliases.ts
packages/admin-ui-core/src/createTheme.ts
packages/admin-ui-core/src/rules.ts
packages/admin-ui-core/src/stories/core.stories.tsx
packages/admin-ui-core/src/tests/create-theme.test.ts
packages/admin-ui-core/src/tokens/breakpoints.ts
packages/admin-ui-core/src/tokens/colors.ts
packages/admin-ui-core/src/tokens/index.ts
packages/admin-ui-core/src/tokens/typography.ts
packages/admin-ui-core/src/types.ts
packages/admin-ui-docs/docs/introduction/developing/styling.mdx
packages/admin-ui-docs/docs/introduction/developing/theming.mdx
packages/admin-ui-react/src/hooks/use-breakpoint.ts
packages/admin-ui-react/src/tests/use-breakpoint.test.tsx

Adds a function to convert the theme into CSS Variables

feat(css-vars): add function to convert the theme into css variables

---

packages/admin-ui-docs/docs/guidelines/experimental/localization.mdx

Adding best practices to localization.mdx as suggested [here](https://vtex.slack.com/archives/C02NJHMAY10/p1657630998137729).
Improving Localization documentation.

docs: add best practices to localization.mdx

---

packages/admin-ui/src/combobox/combobox-multiple-field.tsx

Fix small issue on combobox multiple
When the X on a selected item was clicked in combobox multiple nothing happened
Check if combobox stories work as usual

fix(combobox multiple): delete button not unselecting custom items

---

packages/admin-ui-docs/src/css/markdown.scss

- Optimize body fonts for readability

docs(site): optimize body fonts

---

packages/admin-ui-docs/docs/guidelines/components/toast.mdx
packages/admin-ui-docs/src/css/markdown.scss

docs(toast): review docs

---

packages/admin-ui-docs/content/table/code.mdx
packages/admin-ui-docs/docs/guidelines/components/bulk-actions.mdx
packages/admin-ui/src/bulk-actions/bulk-actions.state.ts
packages/admin-ui/src/bulk-actions/bulk-actions.stories.tsx
packages/admin-ui/src/bulk-actions/bulk-actions.style.ts
packages/admin-ui/src/index.ts
packages/admin-ui/src/table/hooks/use-table-state.tsx
packages/admin-ui/src/table/resolvers/bulk.tsx
packages/admin-ui/src/table/stories/bulk.stories.tsx

It also fixes some bugs:
1. Small change in the Bulk Actions API to work better when we have the page items coming from a request.
2. Fix Table loading skeleton

docs(bulk-actions): add bulk-actions documentation

---

packages/admin-ui-docs/docs/introduction/developing/quick-start.mdx
packages/admin-ui-docs/docs/introduction/developing/theming.mdx

add theme internals documentation

docs(theme): add theme internals documentation

---

packages/admin-ui/src/filters/__stories__/filters-searchable.stories.tsx
packages/admin-ui/src/filters/filter-disclosure.tsx
packages/admin-ui/src/filters/filter-group.state.tsx
packages/admin-ui/src/filters/filter-multiple/filter-multiple.state.tsx
packages/admin-ui/src/filters/filter-multiple/filter-option-checkbox.tsx
packages/admin-ui/src/filters/filter-popover.tsx
packages/admin-ui/src/filters/filter-status.tsx
packages/admin-ui/src/filters/filter.style.tsx
packages/admin-ui/src/filters/filter/filter.state.tsx

Fix some UI and UX issues.
Check all filter stories

fix(filter components): ui fixes

---

packages/admin-ui-docs/content/table/overview.mdx
packages/admin-ui-docs/src/components/CodePreviewContainer/styles.scss
packages/admin-ui/src/table/components/table-cell.tsx
packages/admin-ui/src/table/styles/table-body.styles.ts
packages/admin-ui/src/table/styles/table.styles.ts

update fixed column style and create docs example

refactor(table): update fixed column style

---

packages/admin-ui/src/filters/test/filter-multiple-state.test.ts
packages/admin-ui/src/filters/test/filter-state.test.tsx
packages/admin-ui/src/filters/test/filters.test.tsx

Add tests for filter components and hooks
yarn test filter

Test filters

---

packages/admin-ui/package.json
yarn.lock

fix(admin-ui): update ariakit version

---

packages/admin-ui-react/src/system/create-system.tsx

fix(react): export theme-provider props

---

yarn.lock

fix(lock): refresh yarn.lock

---

packages/admin-ui-core/src/tests/styles.test.ts
packages/admin-ui/src/button/button.tsx
packages/admin-ui/src/combobox/combobox-popover-base.tsx
packages/admin-ui/src/combobox/combobox.stories.tsx
packages/admin-ui/src/components/Collapsible/__stories__/Collapsible.stories.tsx
packages/admin-ui/src/components/Modal/components/ModalDisclosure.tsx
packages/admin-ui/src/components/Sidebar/components/SidebarSectionItem.tsx
packages/admin-ui/src/components/Toolbar/__stories__/Toolbar.stories.tsx
packages/admin-ui/src/filters/filter-control/filter-control.tsx
packages/admin-ui/src/menu/menu-button.tsx
packages/admin-ui/src/radio/radio.style.ts
packages/admin-ui/src/switch/switch.style.ts
packages/admin-ui/src/table/resolvers/image.tsx
packages/admin-ui/src/tag/tag.style.ts
packages/admin-ui/src/tooltip/tooltip.tsx

Update some inner types of the admin-ui components
We are have some type issues when executing `vtex link`

fix: update inner component types

---

packages/admin-ui-docs/blog/2022-08-17.mdx

update last release docs content of filters

docs: update last release docs content

---

packages/admin-ui-docs/content/table/code.mdx
packages/admin-ui/src/table/resolvers/text.tsx

Enable text description to be truncated using ellipsis.
Check the Text resolver section (Code tab)

feat: create prop to enable text description to be truncated (ellipsis)

---

.github/workflows/dev-release.yml
.github/workflows/stable-release.yml

Add job to automate the release process of `dev` and `stable` versions of admin-ui.
This job follows the process described in this diagram:
https://www.notion.so/vtexhandbook/Admin-UI-Release-flow-6ddf38b13b054b9a9dbbe0e3dbb14b6c#a24f8ddd24b54189988eda897a84aa54

ci(github-actions): add dev and stable release automated jobs

---

.github/workflows/dev-release.yml
.github/workflows/stable-release.yml

Release action was returning 403 when trying to publish the packages using the `lerna publish` command.
[You can check the action returning an error here](https://github.com/vtex/admin-ui/actions/runs/3061982663/jobs/4942615232)
[You can check the action with the fix solution here](https://github.com/vtex/admin-ui/actions/runs/3062853250/jobs/4944281265)

ci(github-actions): fix 403 error on lerna publish

---

.github/workflows/ci.yml
.github/workflows/size-limit.yml

You can check the PR comment added by the automation below the description.

ci(size): add size limit job to GH actions

---

packages/admin-ui-docs/package.json
packages/admin-ui-docs/src/components/sandpack/create-file-map.ts
packages/admin-ui-docs/src/components/sandpack/root-code.ts
packages/admin-ui-docs/src/components/sandpack/sandpack.tsx
packages/admin-ui-docs/src/theme/MDXComponents.js

docs(site): add sandpack

---

packages/admin-ui/src/data-view/components/data-view.styles.ts
packages/admin-ui/src/data-view/stories/data-view-actions.stories.tsx
packages/admin-ui/src/pagination/pagination.style.ts
packages/admin-ui/src/pagination/pagination.tsx

Add a static size to the pagination label to avoid layout shift when navigating between pages

fix(pagination): add static size to the pagination label

---

packages/admin-ui-docs/content/page/overview.mdx
packages/admin-ui-docs/content/table/0-133-x/code.mdx
packages/admin-ui-docs/content/table/0-133-x/overview.mdx
packages/admin-ui-docs/content/table/0-133-x/toc.js
packages/admin-ui-docs/content/table/overview.mdx
packages/admin-ui-docs/docs/templates/listing page/code.mdx
packages/admin-ui-docs/src/components/FilterTable/index.tsx
packages/admin-ui-docs/src/components/IconsGrid/index.tsx
packages/admin-ui-docs/src/components/ReleaseNotes.tsx
packages/admin-ui-docs/src/components/SemanticTable.tsx
packages/admin-ui-docs/src/components/StatusTable/index.tsx
packages/admin-ui-docs/src/components/Typeface.tsx
packages/admin-ui-docs/versioned_docs/version-0.133.0/components/table.mdx

docs(table): update documentation with table breaking changes

---

packages/admin-ui/src/filters/filter-disclosure.tsx
packages/admin-ui/src/filters/filter-group.tsx
packages/admin-ui/src/filters/filter.style.tsx

Adjust spacing inside filtergroup
Check storybook

feat(filtergroup): re-add space between filters on a group

---

packages/admin-ui-form/src/form/form.state.ts

export useFieldArray to improve the validation step

feat(form): export useFieldArray to improve the validation step

---

packages/admin-ui-docs/docs/components/data-view.mdx
packages/admin-ui-docs/versioned_docs/version-0.133.0/components/data-view.mdx

docs(data-view): update DataView documentation

---

.github/workflows/stable-release.yml

ci: fix stable release pipeline

---

packages/admin-ui-core/src/styles.ts
packages/admin-ui-core/src/tests/create-theme.test.ts
packages/admin-ui-core/src/tests/get-token-value.test.ts
packages/admin-ui-core/src/tests/mock/admin-ui.config.js

Enable compound css usage for space tokens.
yarn test

Feat compound css

---

packages/admin-ui-docs/docs/templates/listing page/code.mdx

docs(templates): add simple example for listing

---

packages/admin-ui-docs/docs/components/checkbox.mdx

Reviewing Checkbox component documentation and adding design guidelines. This is replicating the changes proposed by pull request #394, but resolving all conflicts, as recommended by @lucasaarcoverde. 
There are two details I would like some help correcting:
- Indentation of bullet points inside the collapsible content.
- Changing collapsible background color to white instead of light blue, as validated [here](https://vtex.slack.com/archives/C01KE2JBL5P/p1662118967488599?thread_ts=1661886230.056799&cid=C01KE2JBL5P) with Davis.

docs: review checkbox.mdx (2)

---

packages/admin-ui-docs/content/radio/design.mdx
packages/admin-ui-docs/content/radio/overview.mdx

Reviewing Radio component documentation and adding design guidelines. This is replicating the changes proposed by pull request #407, but resolving all conflicts, as recommended by @lucasaarcoverde.
There are two details I would like some help correcting:
- Indentation of bullet points inside the collapsible content.
- Changing collapsible background color to white instead of light blue, as validated [here](https://vtex.slack.com/archives/C01KE2JBL5P/p1662118967488599?thread_ts=1661886230.056799&cid=C01KE2JBL5P) with Davis.

docs: review radio component (2) 

---

packages/admin-ui-docs/docs/components/switch.mdx

Reviewing Switch component documentation and adding design guidelines.

docs: review switch.mdx and add design guidelines

---

packages/admin-ui-docs/docs/templates/listing page/overview.mdx

Adding Listing page template overview documentation.

docs: listing page template overview

---

packages/admin-ui-docs/content/tab/code.mdx
packages/admin-ui-docs/content/tab/design.mdx
packages/admin-ui-docs/content/tab/overview.mdx

Reviewing Tab component documentation and updating design guidelines.

docs: review tab component documentation

---

packages/admin-ui-docs/content/button/design.mdx
packages/admin-ui-docs/content/button/overview.mdx

Reviewing Button component documentation and updating design guidelines.

docs: review button component documentation

---

packages/admin-ui-docs/content/menu/code.mdx
packages/admin-ui-docs/content/menu/design.mdx
packages/admin-ui-docs/content/menu/overview.mdx
packages/admin-ui-docs/content/menu/toc.js
packages/admin-ui-docs/docs/components/menu.mdx

Reviewing Menu component documentation and updating design guidelines.

docs: review menu component documentation

---

packages/admin-ui-core/src/stories/core.stories.tsx
packages/admin-ui-core/src/tests/style-variants.test.ts
packages/admin-ui-core/src/tokens/global.ts
packages/admin-ui-docs/src/components/BestPractices.tsx
packages/admin-ui-docs/src/components/CodeBlockWrapper/styles.ts
packages/admin-ui-docs/src/components/ColorCard.tsx
packages/admin-ui-docs/src/components/FilterTable/styles.ts
packages/admin-ui-docs/src/components/IconsGrid/index.tsx
packages/admin-ui-docs/src/components/OrderedList.tsx
packages/admin-ui-docs/src/components/ReleaseNotes.tsx
packages/admin-ui-docs/src/components/SemanticTable.tsx
packages/admin-ui-docs/src/components/Typeface.tsx
packages/admin-ui-form/src/checkbox/stories/checkbox.stories.tsx
packages/admin-ui-form/src/form/stories/form.stories.tsx
packages/admin-ui-form/src/number-input/stories/number-input.stories.tsx
packages/admin-ui-form/src/radio/stories/radio.stories.tsx
packages/admin-ui-form/src/select/stories/select.stories.tsx
packages/admin-ui-form/src/switch/stories/switch.stories.tsx
packages/admin-ui-form/src/text-area/stories/text-area.stories.tsx
packages/admin-ui-form/src/text-input/stories/text-input.stories.tsx
packages/admin-ui-react/src/stories/system.stories.tsx

Migrate all packages to current spacing tokens.

Space tokens packages

---

packages/admin-ui-docs/docs/components/pagination.mdx

Reviewing Pagination component documentation and updating design guidelines.
(recreating https://github.com/vtex/admin-ui/pull/445 as requested by @lucasaarcoverde)

docs: review pagination.mdx

---

packages/admin-ui-docs/docs/documentation/introduction/contributing.mdx
packages/admin-ui-docs/docs/documentation/introduction/working-with-us.mdx

Adding a Working with us page to documentation and editing the Contributing page according to [this task](https://vtex-dev.atlassian.net/browse/EDU-8193) and [this support document](https://www.notion.so/vtexhandbook/Documentation-in-our-website-05e215b68c4a499fb5091e9cbfdad0f0).

docs: adjust content about support and contribution

---

packages/admin-ui-docs/src/components/TokensTable/index.tsx
packages/admin-ui-docs/src/components/TokensTable/tokens.tsx

add space tokens to tokens table on docs
check built docs

docs(spacing tokens): add space tokens to tokens table

---

packages/admin-ui-codemod/bin/cli.js
packages/admin-ui-codemod/src/__tests__/radius-tokens-review.test.js
packages/admin-ui-codemod/src/radius-tokens-review.js

Provide a codemod to migrate border radius token
Making border radius token migration easier
yarn test radius-tokens-review

feat: add border radius token codemod

---

packages/admin-ui/src/filters/filter.i18n.ts

Fix french translation

---

packages/admin-ui/src/table/resolvers/menu.tsx

fix: add mouse event to the table's menu resolver onClick function

---

packages/admin-ui-docs/docs/components/modal.mdx
packages/admin-ui-docs/src/css/custom.scss
packages/admin-ui-docs/src/theme/DocPage/index.js

Modal docs

---

packages/admin-ui-docs/docs/templates/form page/_category_.json
packages/admin-ui-docs/docs/templates/form page/design.mdx

Adding Form Page template design documentation.
[Form template design documentation #468](https://github.com/vtex/admin-ui/issues/468)

docs: add form template design documentation

---

packages/admin-ui-docs/docs/templates/form page/overview.mdx

Adding the Form page template overview documentation. 
[Form template design documentation #468](https://github.com/vtex/admin-ui/issues/468)

docs: add form page template overview

---

packages/admin-ui-docs/docs/templates/getting-started/overview.mdx

Updating the Templates overview documentation with links to the new Form page documentation (created on PR #511).
[Form template design documentation #468](https://github.com/vtex/admin-ui/issues/468)

docs: edit templates overview.mdx

---

packages/admin-ui-docs/docs/templates/listing page/design.mdx

Edit formatting and content in the Listing page template documentation.
Issues raised while working on [Form template design documentation #468](https://github.com/vtex/admin-ui/issues/468)

docs: edit listing page template

---

packages/admin-ui-docs/docs/documentation/introduction/component-status.mdx
packages/admin-ui-docs/src/components/StatusTable/components.tsx
packages/admin-ui-docs/src/components/StatusTable/index.tsx

Update component status classification
Better represent the status of each component

docs: update status table

---

packages/admin-ui-docs/docs/foundations/colors.mdx
packages/admin-ui-docs/docs/foundations/icons.mdx
packages/admin-ui-docs/docs/foundations/spacing.mdx
packages/admin-ui-docs/docs/foundations/typography.mdx

Adding Spacing design documentation as described in issue [#469](https://github.com/vtex/admin-ui/issues/469)

docs: add spacing documentation

---

packages/admin-ui-docs/docs/documentation/introduction/component-status.mdx

docs: fix external links from component status page

---

packages/admin-ui-util/src/__tests__/dom.test.ts
packages/admin-ui-util/src/dom.ts
packages/admin-ui/src/calendar/calendar-cell.ts

The new dataAttr function already existed in another package. So, I renamed it.

fix(util): rename dataAttr function to htmlDataAttr

---

.github/workflows/add-to-project.yml

Add workflow to add new issues to project
Create a new issue then add the "Admin" project to "Projects". That will trigger the automation to add the issue to the project.

ci: add workflow to add issues to project

---

packages/admin-ui-docs/docs/components/search.mdx

Review Search component documentation.

docs: edit search.mdx

---

packages/admin-ui-docs/docs/documentation/introduction/working-with-us.mdx

Update links to schedule a meeting with the team in the Working with us documentation, as requested in [EDU-8740](https://vtex-dev.atlassian.net/browse/EDU-8740).
This is replacing outdated links.
[EDU-8740]: https://vtex-dev.atlassian.net/browse/EDU-8740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: update links in working-with-us.mdx

---

packages/admin-ui-docs/content/tooltip/code.mdx
packages/admin-ui-docs/content/tooltip/design.mdx
packages/admin-ui-docs/content/tooltip/overview.mdx

Reviewing Tooltip component documentation and updating design guidelines.

docs: review tooltip documentation

---

packages/admin-ui-docs/content/filter/design.mdx
packages/admin-ui-docs/content/filter/overview.mdx
packages/admin-ui-docs/content/filter/toc.js
packages/admin-ui-docs/docs/components/filter.mdx

Reviewing Filter component documentation and updating design guidelines.

docs: review filters documentation

---

packages/admin-ui-docs/docs/documentation/introduction/contact-us.mdx
packages/admin-ui-docs/docs/documentation/introduction/contributing.mdx
packages/admin-ui-docs/docs/documentation/introduction/designing.mdx
packages/admin-ui-docs/docs/documentation/introduction/working-with-us.mdx

Creating documentation about designing with Admin UI.
Resolves #473

docs: add designing.mdx

---

packages/admin-ui/src/toast/stories/toast.stories.tsx
packages/admin-ui/src/toast/toast-container.tsx
packages/admin-ui/src/toast/toast.style.ts
packages/admin-ui/src/toast/toast.tsx
packages/admin-ui/src/toast/types.ts
packages/admin-ui/src/toast/use-toast.tsx

BREAKING CHANGE: toast no longer supports csx
Migrate toast to new component model
More efficient model
Check toast story

refactor(toast): change toast to new component model

---

packages/admin-ui/src/tooltip/stories/tooltip.stories.tsx
packages/admin-ui/src/tooltip/tooltip-trigger.tsx
packages/admin-ui/src/tooltip/tooltip.css.ts
packages/admin-ui/src/tooltip/tooltip.tsx

change tooltip to new component model
Check tooltip story

refactor(tooltip): change tooltip to new component model

---

packages/admin-ui/src/card/card-actions.tsx
packages/admin-ui/src/card/card-content.tsx
packages/admin-ui/src/card/card-header.tsx
packages/admin-ui/src/card/card-image.tsx
packages/admin-ui/src/card/card-info.tsx
packages/admin-ui/src/card/card-title.tsx
packages/admin-ui/src/card/card.css.ts
packages/admin-ui/src/card/card.tsx
packages/admin-ui/src/card/stories/card.stories.tsx
packages/admin-ui/src/card/stories/complexity.stories.tsx

BREAKING CHANGE: Csx prop no longer accepted on card
Migrate card to new, more performatic model
Check card story

refactor(card): change card to new component model

---

packages/admin-ui/src/filters/filter.i18n.ts

Fix Spanish messages for the filter component. Tracked in task [LOC-10040](https://vtex-dev.atlassian.net/browse/LOC-10040).
[LOC-10040]: https://vtex-dev.atlassian.net/browse/LOC-10040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix ES messages for filter component

---

packages/admin-ui/src/bulk-actions/bulk-actions.css.ts
packages/admin-ui/src/bulk-actions/bulk-actions.tsx

BREAKING CHANGE: Bulk actions no longer supports the 'csx' prop
Migrating bulk actions to new component model
Check storybook build

refactor(bulk actions): migrate to new component model

---

packages/admin-ui/src/components/SearchBox/intl.tsx

This is part of a series of PRs in several apps to fix German translations and make it available across the Admin. Tracked in task [LOC-9843](https://vtex-dev.atlassian.net/browse/LOC-9843).
Add German translations to SearchBox component.
A test store with DE in the language switcher is [available here](https://localizationqa--obidev.myvtex.com/admin/).
[LOC-9843]: https://vtex-dev.atlassian.net/browse/LOC-9843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add German translations to SearchBox component.

---

packages/admin-ui-docs/content/flex/code.mdx
packages/admin-ui/src/combobox/combobox-multiple-field.tsx
packages/admin-ui/src/data-view/stories/data-view-actions.stories.tsx
packages/admin-ui/src/data-view/stories/data-view.stories.tsx
packages/admin-ui/src/data-view/stories/ui-tests.stories.tsx
packages/admin-ui/src/data-view/stories/with-table.stories.tsx
packages/admin-ui/src/filters/filter-control/filter-control.tsx
packages/admin-ui/src/filters/filter-disclosure.tsx
packages/admin-ui/src/filters/filter.style.tsx
packages/admin-ui/src/flex/flex-spacer.tsx
packages/admin-ui/src/flex/flex.css.ts
packages/admin-ui/src/flex/flex.stories.tsx
packages/admin-ui/src/flex/flex.tsx
packages/admin-ui/src/flex/stories/flex.stories.tsx
packages/admin-ui/src/label/label.stories.tsx
packages/admin-ui/src/pagination/stories/pagination.stories.tsx
packages/admin-ui/src/visually-hidden/stories/visually-hidden.stories.tsx

refactor(flex): migrate

---

packages/admin-ui/src/number-input/number-input.css.ts
packages/admin-ui/src/number-input/number-input.tsx

Breaking change: The number input don't accept the csx property, you must use className instead

feat(number-input): migrate to the new component model

---

packages/admin-ui/src/inline/inline.css.ts
packages/admin-ui/src/inline/inline.stories.tsx
packages/admin-ui/src/inline/inline.tsx

migrate to new component model
Check built stories

refactor(inline): migrate to new component model

---

packages/admin-ui-docs/content/text-input/design.mdx
packages/admin-ui-docs/content/text-input/overview.mdx

Edit TextInput component's design documentation.

docs: edit TextInput documentation

---

packages/admin-ui-docs/docs/components/tag.mdx

Reviewing Tag component documentation and adding design guidelines.

docs: edit tag.mdx

---

packages/admin-ui/src/bulk-actions/bulk-actions.state.ts
packages/admin-ui/src/components/SelectionTree/index.ts
packages/admin-ui/src/index.ts
packages/admin-ui/src/modal/stories/zindexes.stories.tsx
packages/admin-ui/src/selection-tree/index.ts
packages/admin-ui/src/selection-tree/selection-tree-context.ts
packages/admin-ui/src/selection-tree/selection-tree-item.tsx
packages/admin-ui/src/selection-tree/selection-tree-root.tsx
packages/admin-ui/src/selection-tree/selection-tree-state.ts
packages/admin-ui/src/selection-tree/selection-tree.tsx
packages/admin-ui/src/selection-tree/stories/selection-tree.stories.tsx
packages/admin-ui/src/selection-tree/tests/selection-tree-state.test.tsx
packages/admin-ui/src/table/resolvers/selection.tsx
packages/admin-ui/src/table/stories/bulk.stories.tsx
packages/admin-ui/src/table/stories/selectable.stories.tsx

feat(selection-tree): use csm

---

packages/admin-ui-docs/docs/components/bulk-actions.mdx

Edit Bulk Actions component's design documentation.

docs: edit bulk-actions.mdx

---

packages/admin-ui-docs/docs/components/alert.mdx

Review and add design documentation for Alert component.

docs: edit alert.mdx

---

packages/admin-ui-docs/content/table/design.mdx

Fix sections in Table component design documentation, as requested in [EDU-9351](https://vtex-dev.atlassian.net/browse/EDU-9351).
- [] Trivial change (small fix or feature that doesn't impact functionalities)
[EDU-9351]: https://vtex-dev.atlassian.net/browse/EDU-9351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: fix table doc sections

---

packages/admin-ui-docs/content/grid/code.mdx
packages/admin-ui-docs/content/grid/overview.mdx
packages/admin-ui/src/grid/grid-item.tsx
packages/admin-ui/src/grid/grid.css.ts
packages/admin-ui/src/grid/grid.tsx
packages/admin-ui/src/grid/stories/grid.stories.tsx

Breaking change: Grid don't accept the csx property, you must use className instead

feat(grid): migrate to the new component model

---

packages/admin-ui-codemod/bin/cli.js
packages/admin-ui-codemod/src/__tests__/remove-csx.test.js
packages/admin-ui-codemod/src/remove-csx.js

Add codemod to handle box removal and csx removal
yarn workspace @vtex/admin-ui-codemod jest remove-csx
to use it locally: yarn admin-ui-codemod remove-csx ./packages/admin-ui

feat(codemod): add codemod to migrate to new component model

---

packages/admin-ui-core/src/tokens/text.ts
packages/admin-ui-core/src/tokens/typography.ts
packages/admin-ui-docs/src/components/IntroSection/styles.scss
packages/admin-ui-docs/src/components/Page/styles.scss
packages/admin-ui-docs/src/components/PageHeader/styles.ts
packages/admin-ui-docs/src/components/PageSection/styles.scss
packages/admin-ui-docs/src/components/Section/styles.scss
packages/admin-ui-docs/src/css/custom.scss
packages/admin-ui-docs/src/css/markdown.scss

Fix: font width in Safari

---

packages/admin-ui/src/page/page.css.ts

Update max-width to match Figma specifications

Fix: update narrow and standard maxWidth

---

packages/admin-ui/src/filters/filter.css.tsx

Fix spacing above filter popover search

---

.github/ISSUE_TEMPLATE/component-maturity.md

chore(git-template): add component maturity template

---

package.json
packages/next-docs/components/code.tsx
packages/next-docs/next-env.d.ts
packages/next-docs/next.config.js
packages/next-docs/package.json
packages/next-docs/pages/_meta.json
packages/next-docs/pages/design-system/gettings-started.mdx
packages/next-docs/pages/design-system/table.mdx
packages/next-docs/pages/design-system/table/code.mdx
packages/next-docs/pages/design-system/table/design.mdx
packages/next-docs/pages/index.mdx
packages/next-docs/pages/raccoon/getting-started.mdx
packages/next-docs/theme.config.tsx
packages/next-docs/tsconfig.json
yarn.lock

feat(docs): poc next-docs

---

README.md
package.json
packages/docs/pages/index.mdx
packages/docs/pages/index.module.css

- Add note for internal usage on docs
- Add note for internal usage on readme

docs(shoreline): add internal usage only note

---

.github/ISSUE_TEMPLATE/idea.yml

We changed the name from Feature Request to Idea.

chore: Update and rename feature_request.yml to idea.yml

---

.github/ISSUE_TEMPLATE/proposal.yml

chore: Update proposal.yml

---

.github/ISSUE_TEMPLATE/bug_report.yml

The bug template `yml` file was broken and the template wasn't appearing in the issues list

chore: fix bug issue template

---

packages/docs/pages/foundations/border/best-practices.mdx
packages/docs/pages/foundations/color/best-practices.mdx
packages/docs/pages/foundations/elevation/best-practices.mdx
packages/docs/pages/foundations/icons/best-practices.mdx
packages/docs/pages/foundations/radius/best-practices.mdx
packages/docs/pages/foundations/spacing/best-practices.mdx
packages/docs/pages/foundations/typography/best-practices.mdx

Improvements to the documentation

fix: design best practices improvements

---

packages/docs/components/tokens-grid/grid.module.css
packages/docs/components/tokens-grid/grid.tsx
packages/docs/components/tokens-grid/preview-cell.tsx
packages/docs/components/tokens-grid/theme-utils.ts

docs(site): remove $ reference

---

packages/shoreline/src/components/menu/menu.tsx
packages/shoreline/src/components/menu/stories/play.stories.tsx

Resolve #1815 
To disable the menu
```js
<Menu disabled>
{/* ... */}
</Menu>
```

fix(menu): add disabled property

---

packages/shoreline/src/components/filter/filter.tsx
packages/shoreline/src/components/filter/stories/show.stories.tsx

Resolves #1827 
```typescript
<Filter label="Disabled" disabled>
<FilterItem value="Stable">Stable</FilterItem>
<FilterItem value="Experimental">Experimental</FilterItem>
<FilterItem value="Deprecated">Deprecated</FilterItem>
</Filter>
```

fix(filter): add disabled prop

---

packages/shoreline/src/themes/sunrise/components/table.css

Change backgroup color when row is in hover and when the row is selected
fix #1926

fix(table): backgroup color change in hover and selection update

---

packages/shoreline/src/components/text/text.tsx

impruve information about the behavior when variant is context

docs(text): improve text variant property description

---

packages/shoreline/src/themes/sunrise/components/button.css
packages/shoreline/src/themes/sunrise/components/drawer.css
packages/shoreline/src/themes/sunrise/components/icon-button.css
packages/shoreline/src/themes/sunrise/components/modal.css
packages/shoreline/src/themes/sunrise/components/page.css

- Add a min-width for buttons
- Remove the forced styles on parents: Modal, PageHeader, and Drawer

fix(button): add min-width

---

packages/shoreline/src/components/drawer/drawer-dismiss.tsx
packages/shoreline/src/components/drawer/drawer-heading.tsx
packages/shoreline/src/components/drawer/drawer-popover.tsx
packages/shoreline/src/themes/sunrise/components/drawer.css

- Update to Figma specs
- Remove drag
- Enable text selection

fix(drawer): Figma design

---

packages/shoreline/src/components/contextual-help/stories/show.stories.tsx
packages/shoreline/src/components/modal/modal.tsx
packages/shoreline/src/themes/sunrise/components/checkbox.css
packages/shoreline/src/themes/sunrise/components/contextual-help.css
packages/shoreline/src/themes/sunrise/components/drawer.css
packages/shoreline/src/themes/sunrise/components/menu.css
packages/shoreline/src/themes/sunrise/components/modal.css
packages/shoreline/src/themes/sunrise/components/radio.css
packages/shoreline/src/themes/sunrise/components/select.css
packages/shoreline/src/themes/sunrise/components/toast.css
packages/shoreline/src/themes/sunrise/components/tooltip-popover.css

Update multiple z index to fix the issues:
#1971
#1970 
#1935 
#1839 
#1925

fix(z-index): apply the correct z-index tokens on the components

---

packages/docs/pages/guides/how-to-contribute.mdx

Related to https://github.com/vtex/shoreline/issues/1792

docs: add video about github project

---

packages/shoreline/src/components/menu/menu.tsx

Create a new variant for menu that excludes the critical ones.

fix(menu): use the primary, secondary, and tertiary props

---

packages/docs/pages/components/collection/best-practices.mdx
packages/docs/pages/components/pagination/best-practices.mdx
packages/docs/pages/components/table/best-practices.mdx

docs: EDU-10188 New content

---

packages/shoreline/src/themes/sunrise/components/flex.css

fix: flex-wrap typo on flex stylesheet

---

.vtex/catalog-info.yaml
examples/next-14x/next-env.d.ts

This PR adds this component into our software catalog :hugs: 
> Also removes a folder that was hanging there with no use.

chore: add component into dkportal ADMT-654

---

packages/docs/examples/filter-controlled.tsx
packages/docs/examples/filter-custom-msg.tsx
packages/docs/examples/filter-i18n.tsx
packages/docs/examples/filter-multiselect.tsx
packages/docs/examples/filter-search-fetch.tsx
packages/docs/examples/filter-search.tsx
packages/docs/examples/filter-states.tsx
packages/docs/pages/components/filter.mdx

Adds more filter examples to docs

docs: add more filter examples - ADMT-779

---

packages/docs/examples/collection-filter-group.tsx
packages/docs/examples/collection-view-empty-action.tsx
packages/docs/examples/collection-view-empty-custom.tsx
packages/docs/examples/collection-view-error-action.tsx
packages/docs/examples/collection-view-error-custom.tsx
packages/docs/examples/collection-view-not-found-custom.tsx
packages/docs/examples/collection-view-unauthorized-custom.tsx
packages/docs/pages/components/collection/collection-view.mdx

Adds more examples for collection subcomponents

docs: add collections examples - ADMT-778
