vtex/shoreline

packages/admin-ui-react/package.json
packages/admin-ui/package.json
yarn.lock

Update **@vtex/phosphor-icons** version to improve tree-shaking for icons

build(phosphor-icons): bump icons to version 0.2.3

---

packages/admin-ui/src/components/Toast/components/ToastQueue.tsx

Fix toast component width for mobile Devices
Test the toast between 360px and 1200+px, see if it will break
Before this PR sample. (Easily to reproduce it by testing it on mobile < 360px)

fix(toast component): fix toast component width and position for mobile devices

---

packages/admin-ui-react/package.json
packages/admin-ui/package.json
yarn.lock

Update @vtex/phosphor-icons version to improve bundle size of admin-ui

build: bump icons version to 0.2.5

---

packages/admin-ui/package.json
packages/admin-ui/src/components/SearchBox/index.tsx
yarn.lock

The framer-motion lib is only being used on the `SearchBox` component and the problem is that this dep has a bundle size of ~95kb which significantly increases the total bundle of Admin UI
You can compare the [previous animation](https://620e870c28c4ae003a705d42-wgqbiqipek.chromatic.com/?path=/story/admin-ui-searchbox--basic) with the new one (On the storybook preview generated on the PR checks)

fix(bundle-size): remove framer-motion dependency to reduce bundle size

---

packages/admin-ui-react/src/createSystem.tsx

We were downloading VTEX Trust font from a URL in our theme and making the preload of a different one, and in this way we were downloading two fonts every time.
Every time a page using Admin UI is rendered it downloads the VTEX Trust font two times and this can cause performance issues, as shown in the image below where I ran the lighthouse in VTEX admin
You can check that now we are preloading the [same font used in our theme](https://github.com/vtex/admin-ui/blob/main/packages/admin-ui-core/src/values/typography.ts#L8)

fix(font-preload): change url to the right one

---

packages/admin-ui-core/src/styles.ts

Fixes a bug that custom tokens on nested styles are not parsed.
If you create a custom token like:
```js
createSystem({
key: '',
experimentalTheme: merge(theme, {
border: { custom: '5px solid #cecece' }
})
})
```
The following code would work:
```jsx
<Box 
csx={{
border: 'custom'
}}
/>
```
And this other one, don't:
```jsx
<Box 
csx={{
'@tablet': {
border: 'custom'
}
}}
/>
```

fix(admin-ui-core): custom tokens not parsed by csx while nested

---

packages/admin-ui/src/components/Toast/__stories__/Toast.stories.tsx
packages/admin-ui/src/components/Toast/components/Toast.tsx
packages/admin-ui/src/components/Toast/types.ts

To expose the Toast's `csx` props and allow it to be customized.
[These changes are needed to address the Admin Notifications project needs, per Figma specs.](https://www.figma.com/file/zOfC9TCYPQnCXlQ1wKDwmI/Notification-XP-Specs?node-id=1%3A4603)
Currently, Toast's styles are not overridable. This PR allows them to be customizable.
Also, it inherits the `HTMLDivElement` interface, making it possible to alter the Toast's behavior.
[Take a look at the `Custom` Toast from the Storybook preview.](https://admin-ui-toast-csx.surge.sh/?path=/story/admin-ui-toast--playground)

NAD-1035 - Toast: expose `csx` props

---

packages/admin-ui-docs/docs/guidelines/components/alert.mdx
packages/admin-ui-docs/src/components/Page/index.tsx

Add "Design Reference" tab for the Alert component on the doc site.
`yarn docs` locally.

NAD-1080 docs(alert): add design reference tab

---

packages/admin-ui-codemod/bin/cli.js
packages/admin-ui-codemod/src/__tests__/radio-review.test.js
packages/admin-ui-codemod/src/radio-review.js

The Radio review introduces some breaking changes in the Radio and RadioGroup components. This PR adds a codemod to help admin-ui users to migrate to the new version.
**Remove size property**
```jsx
// before
<Radio size="small" />
// after
<Radio />
// before
<RadioGroup size="small" />
// after
<RadioGroup />
```
**Remove Radio state property**
```jsx
// before
<Radio state={state} />
// after
<Radio />
```
**Rename orientation to direction**
```jsx
// before
<RadioGroup orientation="vertical" />
// after
<RadioGroup direction="column" />
// before
<RadioGroup orientation="horizontal" />
// after
<RadioGroup direction="row" />
```

feat(radio): add Radio and RadioGroup codemod

---

packages/admin-ui-form/LICENSE
packages/admin-ui-form/package.json
packages/admin-ui-form/src/form/form.state.ts
packages/admin-ui-form/src/form/form.ts
packages/admin-ui-form/src/form/index.ts
packages/admin-ui-form/src/form/stories/form.stories.tsx
packages/admin-ui-form/src/index.ts
packages/admin-ui-form/src/watch/index.ts
packages/admin-ui-form/src/watch/stories/watch.stories.tsx
packages/admin-ui-form/src/watch/use-watch.ts
packages/admin-ui-form/src/watch/watch.tsx
yarn.lock

Bootstrap of our upcoming form state handling library. Included features:
- useFormState: to keep the state of the form
- Form: the submission element
- useWatch: to subscribe to input changes w/isolate renders
- Watch: render-props version of useWatch
- We must have a consistent, performant, and DX-through form state library.

feat(admin-ui-form): create library w/ form & watch features

---

packages/admin-ui/src/checkbox/__snapshots__/checkbox.test.tsx.snap
packages/admin-ui/src/filters/__tests__/__snapshots__/filter-multiple.test.tsx.snap
packages/admin-ui/src/form-control/__snapshots__/form-control.test.tsx.snap
packages/admin-ui/src/form-control/form-control-message.tsx
packages/admin-ui/src/form-control/form-control.tsx
packages/admin-ui/src/index.ts
packages/admin-ui/src/next.ts
packages/admin-ui/src/radio/__snapshots__/radio.test.tsx.snap
packages/admin-ui/src/switch/__snapshots__/switch.test.tsx.snap
packages/admin-ui/src/text-input/text-input.style.ts
packages/admin-ui/src/text-input/text-input.tsx

- Fix form-control spaces to match Figma.
- Fix form-control message a11y.
- Fix the text-input click/focus behavior.
- Add the `next` terminology to the text-input to avoid confusion.
Admin UI should match Figma and be inclusive to every user.

fix(text-input): a11y, spaces, and next terminology

---

packages/admin-ui-core/package.json
packages/admin-ui-core/src/__stories__/core.stories.tsx
packages/admin-ui-core/src/aliases.ts
packages/admin-ui-core/src/styles.ts
yarn.lock

* Add Stitches [framework agnostic API](https://stitches.dev/docs/framework-agnostic) to the admin-ui-core package and replace the Emotion CSS function with the Stitches one.
* Add a chained selector alias in order to minimize the breaking changes when switching to `Stitches css`
> In Emotion, pseudo-classes and pseudo-selectors are automatically chained to the scoped selector. However, other selectors, such as class or id selectors, require the & sign, otherwise they're considered descendants. 
In Stitches, all chained selectors require the & sign.
[Detailed info about migrating from emotion to Stitches](https://stitches.dev/blog/migrating-from-emotion-to-stitches)
[Detailed info about why choosing the framework agnostic API instead of the …

Add Stitches to admin-ui-core

---

packages/admin-ui-docs/src/components/CodePreviewContainer/index.tsx

Fix code preview container to show menu popover correctly
The menu popover is getting stuck inside the code preview and it should be rendered outside the code preview container.
**Before**
**After**
Check the menu component page

fix: fix code preview container to show menu popover correctly

---

packages/admin-ui/src/combobox/combobox.state.ts

Fix delay on empty state when just one letter is typed on combobox, when the user types just one letter they get the message "start typing". That doesn't make sense
When the user types just one letter they get the message "start typing". That doesn't make sense
https://user-images.githubusercontent.com/8623116/173876068-c9e866dc-4fbb-4150-aa49-2cabc54a1f8d.mov
check combobox on storybook see if issue is fixed, check other states too

fix(combobox): fix delay on empty state when just one letter is typed

---

packages/admin-ui/src/checkbox/checkbox-input.tsx

Update the `aria-checked` with the property value.
The `aria-checked` was set only to `undefined` or `mixed` even when the checkbox was checked.
Check `aria-check` value through inspection (browser)

fix(checkbox): fix aria-checked value

---

packages/admin-ui-docs/src/components/IconsGrid/icons.tsx
packages/admin-ui-docs/src/components/IconsGrid/index.tsx
packages/admin-ui-docs/src/components/TokensTable/index.tsx
packages/admin-ui-docs/src/components/TokensTable/tokens.tsx

- Fix the documentation which today doesn't works the search field for the `Guidelines > Design Tokens` and `Guidelines > Typography`
- Runs `yarn start` on `admin-ui-docs` and try to search something on the `Design Tokens` and `Iconography`

fix(docs): fix search for iconography and design tokens

---

packages/admin-ui/src/inline/inline.tsx

As the title says
`Inline` component was applying `marginLeft` to all nested children, but the correct behavior would be to apply only to the direct children

fix(inline): styles applied not only to direct children but for all nested children

---

packages/admin-ui-core/src/aliases.ts
packages/admin-ui-docs/docs/introduction/developing/styling.mdx
packages/admin-ui-react/src/__tests__/use-breakpoint.test.tsx
packages/admin-ui-react/src/hooks/index.ts
packages/admin-ui-react/src/hooks/use-breakpoint.ts
packages/admin-ui/src/stack/stack.ts

Add a solution that make component properties able to use responsive aliases. This is a replacement for the deprecated way of adding responsiveness to properties using responsive arrays
**Before**
```jsx
<Component prop={[1, 2, 3, 4]} />
<Component prop={[1, 2, null, 4]} />
<Component prop={[1, 2]} />
```
**After**
```jsx
<Component prop={{ mobile: 1, tablet: 2, desktop: 3, widescreen: 4 }} />
<Component prop={{ mobile: 1, tablet: 2, widescreen: 4 }} />
<Component prop={{ mobile: 1, tablet: 2 }} />
```

Add responsive value using the responsive aliases

---

packages/admin-ui/src/menu/menu-button.tsx

Add onClick to MenuButton props
`vtex link` is breaking because it doesn't acknowledge `onClick` as `MenuButton` prop

fix(menu-button): add onClick to MenuButton props

---

packages/admin-ui/src/inline/inline.tsx

Basically, the space applied by the Inline container wasn't being applied to the direct first child but to the container itself, and this was causing a visual breaking change
Check the following screenshots:
**Before**
**After**

fix(inline): space not applied correctly for the current first-child

---

packages/admin-ui-core/src/__tests__/styles.test.ts
packages/admin-ui-core/src/helpers.ts
packages/admin-ui-core/src/styles.ts

Fix the `border` helper function used to apply border styles. The issue is that the function is trying to access the theme colors using a value with the `$` token prefix, but it's necessary to remove it before accessing.
Check that before the components borders weren't being rendered with color, but now everything works.

fix(border): helper function to apply border style not working

---

lerna.json
packages/admin-ui/src/tab/stories/tabs.stories.tsx
packages/admin-ui/src/tab/tab-list.tsx
packages/admin-ui/src/tab/tab-panel-list.tsx
packages/admin-ui/src/tab/tab-panel.tsx
packages/admin-ui/src/tab/tab.tsx

VTEX's IO-Render users are experiencing issues regarding the types while linking. This happens due to an old typescript version used by the platform. This fix generates types in a more explicit/traditional/conventional way.

fix(tab): use explict types instead of deep inheritance

---

packages/admin-ui/src/components/Sidebar/__stories__/Sidebar.stories.tsx
packages/admin-ui/src/components/Sidebar/components/SidebarBackdrop.tsx

Change the Sidebar Skeleton to render always an expanded sidebar. Nowadays is always rendered with a collapsed sidebar

fix(sidebar): section item skeleton not showing in the loading state

---

.storybook/themeDecorator.js
packages/admin-ui-core/src/createTheme.ts
packages/admin-ui-core/src/rules.ts
packages/admin-ui-core/src/styles.ts
packages/admin-ui-core/src/tests/create-theme.test.ts
packages/admin-ui-core/src/tests/styles.test.ts
packages/admin-ui-core/src/theme.ts
packages/admin-ui-core/src/utils.ts
packages/admin-ui-docs/src/theme/Root.js
packages/admin-ui-react/src/stories/system.stories.tsx
packages/admin-ui-react/src/system/create-system.tsx
packages/admin-ui-react/src/test-utils.ts
packages/admin-ui/src/checkbox/utils.ts
packages/admin-ui/src/test-utils.tsx
packages/gatsby-plugin-admin-ui/src/provider.js

Export ThemeProvider without using `createSystem()`

refactor(theme): export ThemeProvider without create system

---

packages/admin-ui/src/tooltip/tooltip-trigger.tsx

Avoid "submit" as the default type of the trigger button
For most browsers the default type of button is "submit", so to avoid a tooltip triggering a submit inside a form, we should set the default type of to "button" (tooltip inner button).

fix(tooltip): avoid "submit" as the default type of the trigger button

---

.storybook/preview.js
packages/admin-ui/src/button/button.stories.tsx

This PR disabled the generation of chromatic snapshots globally. This means that once we update the component stories we can set it as ready to be tested on chromatic and adopt this tool usage incrementally.
[Detailed info](https://www.chromatic.com/docs/ignoring-elements#ignore-stories)

test(chromatic): disable snapshot generation globally

---

packages/admin-ui/src/filters/filter-disclosure.tsx
packages/admin-ui/src/filters/filter.style.tsx
packages/admin-ui/src/filters/filter/filter.state.tsx

Fix spacing on filterListbox when there's scroll.
Change filter to not apply upon selecting (now you must press apply after selecting)
Make "disclosure" have active style whenever popover is open
filters storybook
before:
after:

Feat filter style changes

---

packages/admin-ui/src/table/components/styles/table.styles.ts
packages/admin-ui/src/table/components/table-cell.tsx

Set fixed column position when window is resized
Avoid fix columns with the wrong position when the window is resized and avoid menu component from getting stuck on the table

fix(table): set fixed column position when window is resized

---

packages/admin-ui/src/calendar/calendar-state.ts
packages/admin-ui/src/calendar/utils.ts
packages/admin-ui/src/date-picker/date-picker.stories.tsx
packages/admin-ui/src/i18n/use-region.ts

The datepicker i18n will now depend only on the passed locale, not the browser intl API. This will give more control over the observed date.

fix(datepicker): make datepicker i18n depend only on the passed locale

---

packages/admin-ui/src/tab/stories/tabs.stories.tsx
packages/admin-ui/src/tab/tabs.style.ts

- The disabled styles from tabs is not showing to the user that the tab is not enabled.
- Better UX when using disabled tabs
- `yarn dev && yarn storybook`, then go to disabled Tabs stories
**Before this PR:**
https://user-images.githubusercontent.com/23361175/218422380-9a504765-e20d-4879-bcf1-fa587a0a72cd.mov
**After:**
https://user-images.githubusercontent.com/23361175/218422466-eb851d33-1a79-4cc8-845b-501d7d0b5d5d.mov

fix(tabs): update disabled Tabs' styles

---

packages/admin-ui/src/bleed/bleed.css.ts
packages/admin-ui/src/bleed/bleed.stories.tsx
packages/admin-ui/src/bleed/bleed.tsx
packages/admin-ui/src/combobox/combobox-multiple-field.tsx

🚨 BREAKING CHANGE 🚨: Bleed no longer supports the csx prop, you must use className instead.

feat(bleed): migrate to the new component model

---

packages/admin-ui-docs/content/table/code.mdx
packages/admin-ui-docs/docs/components/data-view.mdx
packages/admin-ui-docs/docs/components/skeleton.mdx
packages/admin-ui/src/filters/filter-status.tsx
packages/admin-ui/src/pagination/pagination.tsx
packages/admin-ui/src/skeleton/skeleton.css.ts
packages/admin-ui/src/skeleton/skeleton.tsx
packages/admin-ui/src/skeleton/stories/skeleton.stories.tsx
packages/admin-ui/src/table/resolvers/bulk.tsx
packages/admin-ui/src/table/resolvers/currency.tsx
packages/admin-ui/src/table/resolvers/date.tsx
packages/admin-ui/src/table/resolvers/image.tsx
packages/admin-ui/src/table/resolvers/menu.tsx
packages/admin-ui/src/table/resolvers/plain.tsx
packages/admin-ui/src/table/resolvers/text.tsx
packages/admin-ui/src/toast/types.ts

🚨 BREAKING CHANGE 🚨: Skeleton no longer supports the csx prop, you must use className instead.

feat(skeleton): migrate to the new component model

---

packages/admin-ui/src/select/select-icon.tsx
packages/admin-ui/src/select/select-input.tsx
packages/admin-ui/src/select/select.css.ts
packages/admin-ui/src/select/select.tsx
packages/admin-ui/src/select/stories/select.stories.tsx

🚨 BREAKING CHANGE 🚨: Select no longer supports the csx prop, you must use className instead.

feat(select): migrate to the new component model

---

packages/admin-ui/src/search/hooks/useSearchState.ts
packages/admin-ui/src/search/search.css.ts
packages/admin-ui/src/search/search.stories.tsx
packages/admin-ui/src/search/search.tsx

🚨 BREAKING CHANGE 🚨: Search no longer supports the csx prop, you must use className instead.
Resolves #572

feat(search): migrate to new component model

---

packages/admin-ui-docs/docs/experimental/date-picker.mdx
packages/admin-ui/src/date-picker/date-picker-calendar.tsx
packages/admin-ui/src/date-picker/date-picker-field.tsx
packages/admin-ui/src/date-picker/date-picker.css.ts

Breaking change: The picker and all its composites don't accept the csx property, you must use className instead

feat(date-picker): migrate to the new component model

---

packages/admin-ui/src/checkbox/checkbox-group.tsx
packages/admin-ui/src/form-control/form-control.tsx
packages/admin-ui/src/page/page.css.ts
packages/admin-ui/src/radio/radio-group.tsx
packages/admin-ui/src/radio/radio.tsx

Wrong spacing in control groups (radio and checkbox groups)

Fix: wrong spacing in control groups

---

packages/admin-ui/src/table/components/table-cell.tsx

- Fixes the React warning about the invalid value for prop `data-horizontal-scroll`
```bash
Warning: Invalid value for prop `data-horizontal-scroll` on <td> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior
```
- Fixes the value, which was invalid before, so it couldn't be used.

TableCell: invalid value for prop data-horizontal-scroll

---

packages/admin-ui/src/form-control/form-control.tsx

I wanted to change the space only on the Radio Group and Checkbox group components, but I ended up breaking Input components. I think "Form Control" should only be used by Radio Group and Checkbox Group components, and there should be a "Form Input" component for the inputs. Radio and Checkbox are controls and the other fields are inputs.
But since it might take sometime to make this change, and the inputs are broken, I'm reverting my previous commit in this PR.

Fix form control spacing

---

packages/shoreline/src/components/collection/collection-view.tsx
packages/shoreline/src/components/collection/stories/show.stories.tsx
packages/shoreline/src/components/collection/tests/collections.test.tsx

fix #1652
Explaned in the [issue](https://github.com/vtex/shoreline/issues/1652)

fix(collection-view): change to actions only appear if onError or onEmpty are passed

---

packages/shoreline/src/components/date-picker/date-picker.tsx
packages/shoreline/src/themes/sunrise/components/date-picker.css

Border radius of calendar IconButton inside date picker input changed from `$radius-2` to `$radius-1`
fix #1583

fix(date-picker): change the border radius of the calendar IconButton

---

README.md
packages/docs/pages/guides/code/development-guideline.mdx
packages/docs/pages/guides/contributing-introduction.mdx
packages/docs/pages/guides/design/handoff-requirements.mdx
packages/docs/pages/guides/getting-started.mdx
packages/docs/pages/guides/how-to-contribute.mdx
packages/docs/pages/guides/styling/introduction.mdx

Fix some broken doc links.
- https://shoreline.vtex.com/guides/theming/introduction
- https://shoreline.vtex.com/guides/engineering-contribution/development-guideline

docs(broken links): update broken links in the docs

---

packages/shoreline/src/components/field/stories/show.stories.tsx
packages/shoreline/src/themes/sunrise/components/field.css

changes the component's styles so that it does not have a fixed width, but rather a minimum width, so that it can respect an increase in size requested by the parent (justify: 'stretch', for example)
fix #1787

fix(field): fix width style

---

packages/shoreline/src/components/search/messages/bg.json
packages/shoreline/src/components/search/messages/de.json
packages/shoreline/src/components/search/messages/en.json
packages/shoreline/src/components/search/messages/es.json
packages/shoreline/src/components/search/messages/fr.json
packages/shoreline/src/components/search/messages/index.ts
packages/shoreline/src/components/search/messages/it.json
packages/shoreline/src/components/search/messages/ja.json
packages/shoreline/src/components/search/messages/ko.json
packages/shoreline/src/components/search/messages/nl.json
packages/shoreline/src/components/search/messages/pt.json
packages/shoreline/src/components/search/messages/ro.json
packages/shoreline/src/components/search/messages/th.json
packages/shoreline/src/components/search/search.tsx
packages/shoreline/src/components/search/stories/play.stories.tsx
packages/shoreline/src/components/search/tests/search.test.tsx

Fix the **Search** component placeholder.

fix(search): add traslation for default placeholder of search component

---

crowdin.yml
packages/docs/pages/guides/code/component-model.mdx

Add a crowdin pattern to messages folder which eliminates the need for initial configuration, component by component
note: I've already used this configuration format, but since I can't test it locally, I think it's worth talking to someone in the localization (I think they might only be able to check after the merge)

fix: Crowdin file

---

packages/shoreline/src/components/confirmation-modal/confirmation-modal.tsx

Allow confirmation modals to be disabled
```jsx
<ConfirmationModal disabled={value === ''}>
<Input value={value} />
</ConfirmationModal>
```

feat(confirmation-modal): add disabled prop

---

packages/shoreline/src/components/confirmation-modal/confirmation-modal.tsx

Allow confirmation modals to be critical. 
```jsx
<ConfirmationModal critical>
<Text>Are you sure?</Text>
</ConfirmationModal>
```

feat(confirmation-modal): add critical prop

---

packages/docs/pages/guides/code/development-guideline.mdx

This was kind of a bad grammar mistake, the page will be a little bit nicer with it corrected.

docs: fix typo in development-guideline

---

packages/shoreline/src/themes/sunrise/components/input.css

Input does not have height padding, so the click does not work.

fix: add height property to input component

---

packages/docs/scripts/build-contributors.mjs

Related to #1859 
An error occurs every time you try to run the documentation build locally. This happens because we are generating some GitHub metrics for our [activity]() page that requires a GitHub token, when you don't have this set it breaks the documentation site. This PR fix it

docs: fix local build error

---

packages/docs/pages/foundations/color.mdx
packages/docs/pages/foundations/index.mdx

fix #1764
Change colors order to prioritize semantics colors over primitives
Fix group of color title - from base to primitives

docs(fundations): change the order of colors 

---

packages/shoreline/src/components/collection/collection-view.tsx
packages/shoreline/src/components/collection/stories/show.stories.tsx
packages/shoreline/src/themes/sunrise/components/collection-view.css

Resolves #1825 
```typescript
<CollectionView
status="empty"
messages={{
'empty-heading':
'No products created inside this category yet.',
'empty-description': 'Use the button below to create a new product',
'empty-action': 'Create product',
}}
onEmpty={() => alert('On empty action')}
>
<div className="ready-view" />
</CollectionView>
```

fix(collection-view): heading aligment to the center

---

packages/shoreline/src/components/page/stories/show.stories.tsx
packages/shoreline/src/themes/sunrise/components/page.css

The current selector increased the size for icon-only buttons, causing a style bug, so change the selector to be more specific
fix #1830
Before
After

fix(page): change selector that changes button width to be more specific

---

packages/ts-table/package.json

Before the peer dependency to vtex/shoreline as fixed in the 1.x major, generating warnings when the user uses the latest versions of the packages. Now, the user can use `>=1`, withous warnings
fix #1826

build(ts-table): fix the shoreline package peer dependency version

---

packages/shoreline/src/components/toast/toast-stack.tsx
packages/shoreline/src/components/toast/toast.tsx

Resolves #1536 
```typescript
// Renders the Toast component with role equal alert and aria-live equal assertive
<ToastStack toastOptions={
{
ariaProps: {
role: 'alert',
"aria-live": 'assertive'
}
}
} />
```

fix(toast-stack): pass custom ariaProps to the Toast component

---

packages/shoreline/src/components/toast/stories/examples.stories.tsx
packages/shoreline/src/components/toast/toast-function.ts

Resolves #1605 
```typescript
// To cleanup all toasts
<Button
onClick={() => {
toast.dismiss()
}}
>
Cleanup all
</Button>
// To cleanup specific toast
<Button
onClick={() => {
const id = toast.loading('Loading...')
setTimeout(() => toast.dismiss(id), 2000)
}}
>
Cleanup loading toast after 2 seconds!
</Button>
```

fix(toast-function): pass dismiss method from lib

---

packages/shoreline/src/components/skeleton/skeleton.tsx
packages/shoreline/src/components/skeleton/stories/show.stories.tsx
packages/shoreline/src/themes/sunrise/components/skeleton.css

Adding this props avoid creating a CSS style every time a skeleton is used
fix #1829

feat(skeleton): add width and height props to set the skeleton size

---

packages/docs/pages/guides/code/component-model.mdx

Add info about the pattern that must be followed to enable override of component messages
fix #1777

docs(contributiong/code/component model): add information about internationalization

---

packages/shoreline/src/themes/sunrise/components/tab.css

In the current style miss the `>` symbol, causing the style to not be applied correctly
fix #1849
After:
Before:

fix(tab): color to selected tab

---

packages/shoreline/src/components/index.ts

For the same reasons related in #1852, the other components has the props ans options interfaces exported, but Text component hasn't. This dificult make extensions to be used in the apps

refactor(text): add export to TextOptions interface

---

packages/shoreline/src/components/text/stories/show.stories.tsx
packages/shoreline/src/components/text/text.tsx
packages/shoreline/src/themes/sunrise/components/text.css

Adds support for the `color` prop to the `Text` component. It closes https://github.com/vtex/shoreline/issues/1855.
```tsx
function ErrorText({ text }) {
return <Text variant="body" color="#FF0000">{text}</Text>
}
```
```tsx
function StatusText({ text }) {
return <Text variant="body" color="var(--status-text)">{text}</Text>
}
```

feat(text): add `color` prop support

---

packages/shoreline/src/components/locale/create-message-hook.ts
packages/shoreline/src/components/locale/tests/create-message-hook.test.tsx

Change the way to replace the dinamyc values to not be necessary that it is rounded by empty spaces
fix #1896
It is possible to see an example that was used to test the feature in the test file

fix(create-message-hook): dynamic values is not a isolated word

---

packages/shoreline/src/themes/sunrise/components/table.css

Change backgroup color when row is in hover and when the row is selected (fix commit 5f331186c958)
fix #1926
Fix erro from lint:css in pr #1928

fix(table): backgroup color change in hover and selection update

---

packages/docs/pages/components/toast/best-practices.mdx

As the title says. Redoing #1915 because of conflicts.

Update toast timing in best practices

---

packages/docs/components/icons-grid/icons.ts

As the title says. Redoing #1828 because of conflicts.

(docs): Include icon synonyms

---

packages/shoreline/src/themes/sunrise/components/ts-table.css

change from height to max-heigth in the css for virtualized table to avoid style issues when has few items in the list
fix #1893

fix(ts-table): css to ts-table virtualize

---

packages/shoreline/src/components/contextual-help/contextual-help.tsx

It is necessary change from Button to IconButton to fix the min width, that needs be as icon button (auto) and not regular button (min width with fixed size)
fix #1967
Before:
After:

fix(contextual-help): change to use IconButton instance of Button

---

packages/shoreline/src/themes/sunrise/components/toast.css

This is necessary to ensure that the font setting is applied correctly regardless of where the toast stack is instantiated
fix #1978

fix(toast): add font style to data-sl-toast

---

packages/shoreline/src/components/date-picker/date-picker.tsx
packages/shoreline/src/components/menu/menu-popover.tsx
packages/shoreline/src/components/popover/popover.tsx

Currently we have this problem: [1980](https://github.com/vtex/shoreline/issues/1980).
To fix it, it's necessary to disable portal prop when using Menu and DataPicker, according to discussion at [this thread](https://vtex.slack.com/archives/C01DVTFA4VA/p1727380818432499).
To make this possible, it's necessary to add portal prop to DatePicker, MenuPopover and Popover components, so it's possible to define portal as `false` when using MenuPopover or DataPicker.
Before
```javascript
<Menu label="Open menu">
<MenuItem>Item 1</MenuItem>
<MenuItem>Item 2</MenuItem>
</Menu>
```
https://github.com/user-attachments/assets/7f333af3-7d65-4917-bc9a-85f98623adf0
```javascript
<MenuProvider>
<MenuTrigger asChild>
<Button>Open menu</Button>
</MenuTrigger>
<MenuPopover portal={false}>
<MenuItem>Item …
```

fix(1980): add portal option to DatePicker, MenuPopover, and Popover components

---

packages/shoreline/src/components/clickable/clickable-bubble.tsx
packages/shoreline/src/components/clickable/clickable.tsx
packages/shoreline/src/components/clickable/stories/examples.stories.tsx

This new property will define whether the ClickableBubble will allow the bubble of only its immediate child or of all its internal children.
fix #1963
The new stories added

feat(clickable): add only immediate prop

---

packages/shoreline/src/components/input/input.tsx

The disabled prop is not being passed to the native input element, is only applying the disabled style
[Codesandbox](https://codesandbox.io/p/sandbox/2jxclc)

fix(input): pass disabled to native input

---

packages/shoreline/src/components/calendar/calendar-grid.tsx

change the key used to be the week day character plus the index to avoid warnings when diferents days have the semana character for identification
fix #2041

fix(calendar-grid): change key used in week days mapping

---

packages/shoreline/src/components/date-picker/date-picker.tsx
packages/shoreline/src/components/date-range-picker/date-range-picker.tsx

fix: datepicker custom id

---

packages/shoreline/src/components/date-picker/date-picker.tsx
packages/shoreline/src/components/date-picker/stories/examples.stories.tsx
packages/shoreline/src/components/date-range-picker/date-range-picker.tsx
packages/shoreline/src/components/date-range-picker/stories/examples.stories.tsx
packages/shoreline/src/themes/sunrise/components/date-picker.css
packages/shoreline/src/themes/sunrise/components/date-range-picker.css

fixes #2048
Can be checked in the storybook created for each component

fix: adjust date-picker disabled prop

---

packages/shoreline/src/themes/sunrise/components/checkbox.css
packages/ts-table/src/stories/virtualized-selection.stories.tsx

fix(ts-table): interaction between getSelectionColumn and Virtualization

---

packages/shoreline/src/components/filter/filter-clear.tsx

Solves this issue: https://github.com/vtex/shoreline/issues/2064
Now multi select filter's clear button renders as disabled correctly when the value is an empty array, not only with empty strings (or other falsy values). The behaviour is now the same for single item (radio) or multiple item (checkbox) filters.
This behavior can be observed in the `Filter` `Show` story:
```jsx
<Filter label="Multiple status" defaultValue={[]}>
<FilterItem value="Stable">Stable</FilterItem>
<FilterItem value="Experimental">Experimental</FilterItem>
<FilterItem value="Deprecated">Deprecated</FilterItem>
</Filter>
```
renders the clear button as disabled when it has no value and nothing is selected
and still renders it enabled when an item is selected
or if it has an item already applied
```jsx
<Filter …
```

fix(filter-clear): disable clear button when value is empty array

---

packages/shoreline/src/components/select/select.tsx

The Select component accepts a `className` prop and even destructures it internally, however it never applies it to any element.
This adds `className` to the `data-sl-select` div.
Select ignores className:
https://codesandbox.io/p/sandbox/eloquent-chatelet-kkvrpg

fix(select): add missing className to select div

---

.github/workflows/release.yml

As per the [deprecation notice](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) states from Github:
>Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact)
Since SL currently uses V3, all releases merged to main won't fulfill starting today. That said, we must update the artifact to V4 asap.
[Sophia's run failing](https://github.com/vtex/shoreline/actions/runs/13059615071)

chore: update release GH worflow upload-artifact to v4

---

packages/shoreline/src/components/drawer/drawer-popover.tsx
packages/shoreline/src/components/drawer/stories/popover-as-child.stories.tsx

Addresses the issue seen on #2072 which was proposed a workaround, and now is fully supported by the lib.
I've added a story to the Drawer as a reference to the issue scenario. It can be used as an example: https://github.com/vtex/shoreline/blob/fix/add-as-child-to-drawer-popover/packages/shoreline/src/components/drawer/stories/popover-as-child.stories.tsx

fix(drawer-popover): properly pass `asChild` as a valid prop

---

packages/shoreline/src/components/index.ts

fix(select): add missing exports from the global index

---

packages/shoreline/src/components/stack/stories/depth.stories.tsx
packages/shoreline/src/themes/sunrise/components/stack.css

Fix https://github.com/vtex/shoreline/issues/1684
A story was added with the following code:
```
export function Depth() {
return (
<div className="App">
<p style={{ margin: '0 0 var(--sl-space-2)' }}>With two coluns:</p>
<Stack space="$space-10" horizontal>
<Stack space="$space-1">
<div style={itemStyle}>Col A 1</div>
<div style={itemStyle}>Col A 2</div>
<div style={itemStyle}>Col A 3</div>
</Stack>
<Stack space="$space-1">
<div style={itemStyle}>Col B 1</div>
<div style={itemStyle}>Col B 2</div>
<div style={itemStyle}>Col B 3</div>
</Stack>
</Stack>
<p style={{ margin: 'var(--sl-space-10) 0 var(--sl-space-2)' }}>
With three coluns:
</p>
<Stack space="$space-20" horizontal>
<Stack space="$space-10">
<div style={itemStyle}>Col A 1</div>
<div style={itemStyle}>Col A 2</div>
<div …
```

fix: Bug in Nested Stacks
